# Medidas DAX — tabela _medidas em desafio-analista-de-dados-myde-lucas-a-goncalves.pbix
# Tabelas via ODBC (MariaDB 3.2) | Calendário: dim_calendar

-- Valor total emprestado
Valor Total Emprestado = SUM(fact_loan[amount])

-- Ticket médio
Ticket Médio Empréstimo = AVERAGE(fact_loan[amount])

-- Quantidade de empréstimos
Qtd Empréstimos = COUNTROWS(fact_loan)

-- Empréstimos maus (B/D)
Qtd Empréstimos Maus = CALCULATE(
    COUNTROWS(fact_loan),
    fact_loan[status_grupo] = "mau"
)

-- Taxa de inadimplência (%)
Taxa Inadimplência = DIVIDE(
    [Qtd Empréstimos Maus],
    [Qtd Empréstimos],
    0
)

-- Contas ativas
Qtd Contas = DISTINCTCOUNT(dim_account[account_id])

-- Clientes ativos
Qtd Clientes = DISTINCTCOUNT(dim_client[client_id])

-- Cartões ativos
Qtd Cartões = DISTINCTCOUNT(dim_card[card_id])

-- Concessões / valor no período — dim_calendar[Date] -> fact_loan[loan_date] já está ativo
Concessões no Período = [Qtd Empréstimos]

Valor Concedido no Período = [Valor Total Emprestado]

-- Transações por data (só se precisar — relação trans_date está inativa)
Valor Transações no Período =
CALCULATE(
    SUM(fact_trans[amount]),
    USERELATIONSHIP(dim_calendar[Date], fact_trans[trans_date])
)

-- Inadimplência por região (via dim_district)
Taxa Inadimplência Região = DIVIDE(
    CALCULATE([Qtd Empréstimos Maus], dim_district),
    CALCULATE([Qtd Empréstimos], dim_district),
    0
)

-- Formatação: Taxa Inadimplência e Taxa Inadimplência Região → %
